"""What smTOOLS_COMPUTER_CLI_01 is supposed to know: one entry per job, with the command for each platform.

This file is the ground truth. The generator makes training messages from it, the checker scores against it,
and a person can read it to see exactly what the model is being taught.

Each task has:
    id       a short name
    about    what the job is, in plain words
    slots    the parts a person fills in, like a port number or a package name
    risk     read (looks only), write (changes files), install, admin (needs root), destructive (hard to undo)
    say      ways people ask for it, with {slots} in them
    cmd      the command per platform, with the same {slots}

Platforms: ubuntu (apt, systemd, GNU tools), fedora (dnf), arch (pacman), macos (brew, BSD tools, launchd),
windows (PowerShell 5+, winget).

Honesty note: the Linux and Windows commands are written from knowledge, not run here. Only macOS commands can
be tried on this machine. check.py syntax-checks every POSIX command; Windows ones are unverified.
"""

PLATFORMS = ["ubuntu", "fedora", "arch", "macos", "windows"]
SHELLS = {"ubuntu": "bash", "fedora": "bash", "arch": "bash", "macos": "zsh", "windows": "powershell"}
RISKS = ["read", "write", "install", "admin", "destructive"]

TASKS = [
    # ----- files and folders -----
    {"id": "list_files", "about": "list the files here", "slots": [], "risk": "read",
     "say": ["list the files here", "what's in this folder", "show me the files", "ls with details", "what files are in this directory"],
     "cmd": {"ubuntu": "ls -la", "fedora": "ls -la", "arch": "ls -la", "macos": "ls -la", "windows": "Get-ChildItem -Force"}},
    {"id": "list_path", "about": "list the files in a folder", "slots": ["path"], "risk": "read",
     "say": ["list the files in {path}", "what's in {path}", "show me what's inside {path}", "contents of {path}"],
     "cmd": {"ubuntu": "ls -la {path}", "fedora": "ls -la {path}", "arch": "ls -la {path}", "macos": "ls -la {path}",
             "windows": "Get-ChildItem -Force {path}"}},
    {"id": "show_file", "about": "print a file", "slots": ["path"], "risk": "read",
     "say": ["show me {path}", "print {path}", "cat {path}", "what's in the file {path}", "read {path}"],
     "cmd": {"ubuntu": "cat {path}", "fedora": "cat {path}", "arch": "cat {path}", "macos": "cat {path}",
             "windows": "Get-Content {path}"}},
    {"id": "tail_log", "about": "follow a log file as it grows", "slots": ["path"], "risk": "read",
     "say": ["follow {path}", "tail {path}", "watch {path} live", "show me new lines in {path} as they come"],
     "cmd": {"ubuntu": "tail -f {path}", "fedora": "tail -f {path}", "arch": "tail -f {path}", "macos": "tail -f {path}",
             "windows": "Get-Content {path} -Wait -Tail 20"}},
    {"id": "find_by_name", "about": "find a file by name", "slots": ["name", "path"], "risk": "read",
     "say": ["find {name} under {path}", "where is {name} in {path}", "search {path} for a file called {name}",
             "locate {name} inside {path}"],
     "cmd": {"ubuntu": "find {path} -name '{name}'", "fedora": "find {path} -name '{name}'", "arch": "find {path} -name '{name}'",
             "macos": "find {path} -name '{name}'", "windows": "Get-ChildItem -Path {path} -Filter '{name}' -Recurse"}},
    {"id": "grep_text", "about": "search files for a piece of text", "slots": ["text", "path"], "risk": "read",
     "say": ["find {text} in {path}", "search {path} for {text}", "which files under {path} mention {text}",
             "grep {text} in {path}"],
     "cmd": {"ubuntu": "grep -rn '{text}' {path}", "fedora": "grep -rn '{text}' {path}", "arch": "grep -rn '{text}' {path}",
             "macos": "grep -rn '{text}' {path}",
             "windows": "Get-ChildItem -Path {path} -Recurse -File | Select-String -Pattern '{text}'"}},
    {"id": "make_dir", "about": "make a folder", "slots": ["path"], "risk": "write",
     "say": ["make a folder called {path}", "create the directory {path}", "mkdir {path}", "new folder {path}"],
     "cmd": {"ubuntu": "mkdir -p {path}", "fedora": "mkdir -p {path}", "arch": "mkdir -p {path}", "macos": "mkdir -p {path}",
             "windows": "New-Item -ItemType Directory -Force -Path {path}"}},
    {"id": "copy_path", "about": "copy a file or folder", "slots": ["src", "dst"], "risk": "write",
     "say": ["copy {src} to {dst}", "duplicate {src} into {dst}", "cp {src} {dst}"],
     "cmd": {"ubuntu": "cp -r {src} {dst}", "fedora": "cp -r {src} {dst}", "arch": "cp -r {src} {dst}", "macos": "cp -r {src} {dst}",
             "windows": "Copy-Item -Recurse {src} {dst}"}},
    {"id": "move_path", "about": "move or rename", "slots": ["src", "dst"], "risk": "write",
     "say": ["move {src} to {dst}", "rename {src} to {dst}", "mv {src} {dst}"],
     "cmd": {"ubuntu": "mv {src} {dst}", "fedora": "mv {src} {dst}", "arch": "mv {src} {dst}", "macos": "mv {src} {dst}",
             "windows": "Move-Item {src} {dst}"}},
    {"id": "delete_file", "about": "delete a file", "slots": ["path"], "risk": "destructive",
     "say": ["delete {path}", "remove the file {path}", "rm {path}", "get rid of {path}"],
     "cmd": {"ubuntu": "rm {path}", "fedora": "rm {path}", "arch": "rm {path}", "macos": "rm {path}",
             "windows": "Remove-Item {path}"}},
    {"id": "delete_dir", "about": "delete a folder and everything in it", "slots": ["path"], "risk": "destructive",
     "say": ["delete the folder {path}", "remove {path} and everything in it", "rm -rf {path}", "wipe the directory {path}"],
     "cmd": {"ubuntu": "rm -rf {path}", "fedora": "rm -rf {path}", "arch": "rm -rf {path}", "macos": "rm -rf {path}",
             "windows": "Remove-Item -Recurse -Force {path}"}},
    {"id": "count_lines", "about": "count the lines in a file", "slots": ["path"], "risk": "read",
     "say": ["how many lines is {path}", "count the lines in {path}", "wc -l {path}", "line count of {path}"],
     "cmd": {"ubuntu": "wc -l {path}", "fedora": "wc -l {path}", "arch": "wc -l {path}", "macos": "wc -l {path}",
             "windows": "(Get-Content {path}).Count"}},
    {"id": "replace_in_file", "about": "replace text inside a file", "slots": ["a", "b", "path"], "risk": "write",
     "say": ["replace {a} with {b} in {path}", "swap {a} for {b} in the file {path}", "change every {a} to {b} in {path}"],
     "cmd": {"ubuntu": "sed -i 's/{a}/{b}/g' {path}", "fedora": "sed -i 's/{a}/{b}/g' {path}", "arch": "sed -i 's/{a}/{b}/g' {path}",
             "macos": "sed -i '' 's/{a}/{b}/g' {path}",
             "windows": "(Get-Content {path}) -replace '{a}','{b}' | Set-Content {path}"}},
    {"id": "file_perms", "about": "change what a file allows", "slots": ["path"], "risk": "admin",
     "say": ["make {path} readable and writable by me only", "chmod 600 {path}", "lock down the permissions on {path}"],
     "cmd": {"ubuntu": "chmod 600 {path}", "fedora": "chmod 600 {path}", "arch": "chmod 600 {path}", "macos": "chmod 600 {path}",
             "windows": "icacls {path} /inheritance:r /grant:r \"$env:USERNAME:(F)\""}},
    {"id": "make_executable", "about": "let a script run", "slots": ["path"], "risk": "write",
     "say": ["make {path} executable", "chmod +x {path}", "let me run {path}"],
     "cmd": {"ubuntu": "chmod +x {path}", "fedora": "chmod +x {path}", "arch": "chmod +x {path}", "macos": "chmod +x {path}",
             "windows": "Unblock-File {path}"}},
    {"id": "change_owner", "about": "change who owns a file", "slots": ["user", "path"], "risk": "admin",
     "say": ["give {user} ownership of {path}", "chown {path} to {user}", "make {user} the owner of {path}"],
     "cmd": {"ubuntu": "sudo chown -R {user} {path}", "fedora": "sudo chown -R {user} {path}", "arch": "sudo chown -R {user} {path}",
             "macos": "sudo chown -R {user} {path}", "windows": "icacls {path} /setowner {user} /T"}},

    # ----- disk -----
    {"id": "disk_free", "about": "how much disk space is left", "slots": [], "risk": "read",
     "say": ["how much disk space is left", "am I running out of space", "df", "show free space on my drives"],
     "cmd": {"ubuntu": "df -h", "fedora": "df -h", "arch": "df -h", "macos": "df -h",
             "windows": "Get-PSDrive -PSProvider FileSystem"}},
    {"id": "folder_size", "about": "how big a folder is", "slots": ["path"], "risk": "read",
     "say": ["how big is {path}", "size of the folder {path}", "du {path}", "how much space does {path} take"],
     "cmd": {"ubuntu": "du -sh {path}", "fedora": "du -sh {path}", "arch": "du -sh {path}", "macos": "du -sh {path}",
             "windows": "Get-ChildItem {path} -Recurse -File | Measure-Object -Property Length -Sum"}},
    {"id": "biggest_folders", "about": "which folders here take the most space", "slots": [], "risk": "read",
     "say": ["what's taking up space here", "biggest folders in this directory", "which folders are the largest",
             "show me the space hogs in this folder"],
     "cmd": {"ubuntu": "du -h --max-depth=1 . | sort -rh | head -10", "fedora": "du -h --max-depth=1 . | sort -rh | head -10",
             "arch": "du -h --max-depth=1 . | sort -rh | head -10", "macos": "du -h -d 1 . | sort -rh | head -10",
             "windows": "Get-ChildItem -Directory | ForEach-Object { [PSCustomObject]@{ Name = $_.Name; MB = [math]::Round((Get-ChildItem $_.FullName -Recurse -File | Measure-Object Length -Sum).Sum / 1MB, 1) } } | Sort-Object MB -Descending | Select-Object -First 10"}},
    {"id": "biggest_files", "about": "the biggest files under a folder", "slots": ["path"], "risk": "read",
     "say": ["biggest files in {path}", "what are the largest files under {path}", "find big files in {path}"],
     "cmd": {"ubuntu": "find {path} -type f -printf '%s %p\\n' | sort -rn | head -10",
             "fedora": "find {path} -type f -printf '%s %p\\n' | sort -rn | head -10",
             "arch": "find {path} -type f -printf '%s %p\\n' | sort -rn | head -10",
             "macos": "find {path} -type f -exec ls -l {} + | sort -k5 -rn | head -10",
             "windows": "Get-ChildItem {path} -Recurse -File | Sort-Object Length -Descending | Select-Object -First 10 Name,Length"}},
    {"id": "list_mounts", "about": "what drives are mounted", "slots": [], "risk": "read",
     "say": ["what drives are mounted", "list my mounts", "show mounted volumes", "what disks are attached"],
     "cmd": {"ubuntu": "lsblk -f", "fedora": "lsblk -f", "arch": "lsblk -f", "macos": "diskutil list",
             "windows": "Get-Volume"}},

    # ----- processes -----
    {"id": "list_processes", "about": "what's running", "slots": [], "risk": "read",
     "say": ["what's running", "list the processes", "show me running programs", "ps"],
     "cmd": {"ubuntu": "ps aux", "fedora": "ps aux", "arch": "ps aux", "macos": "ps aux", "windows": "Get-Process"}},
    {"id": "top_cpu", "about": "what's using the CPU", "slots": [], "risk": "read",
     "say": ["what's eating my CPU", "top CPU processes", "why is my machine slow", "what's using the processor"],
     "cmd": {"ubuntu": "ps aux --sort=-%cpu | head -10", "fedora": "ps aux --sort=-%cpu | head -10",
             "arch": "ps aux --sort=-%cpu | head -10", "macos": "ps aux -r | head -10",
             "windows": "Get-Process | Sort-Object CPU -Descending | Select-Object -First 10"}},
    {"id": "top_memory", "about": "what's using memory", "slots": [], "risk": "read",
     "say": ["what's using all my memory", "top memory processes", "which program is hogging RAM"],
     "cmd": {"ubuntu": "ps aux --sort=-%mem | head -10", "fedora": "ps aux --sort=-%mem | head -10",
             "arch": "ps aux --sort=-%mem | head -10", "macos": "ps aux -m | head -10",
             "windows": "Get-Process | Sort-Object WorkingSet -Descending | Select-Object -First 10"}},
    {"id": "find_process", "about": "find a process by name", "slots": ["name"], "risk": "read",
     "say": ["is {name} running", "find the {name} process", "check if {name} is running", "pgrep {name}"],
     "cmd": {"ubuntu": "pgrep -a {name}", "fedora": "pgrep -a {name}", "arch": "pgrep -a {name}", "macos": "pgrep -l {name}",
             "windows": "Get-Process -Name {name} -ErrorAction SilentlyContinue"}},
    {"id": "kill_name", "about": "stop a program by name", "slots": ["name"], "risk": "destructive",
     "say": ["kill {name}", "stop the {name} process", "force quit {name}", "shut down {name}"],
     "cmd": {"ubuntu": "pkill {name}", "fedora": "pkill {name}", "arch": "pkill {name}", "macos": "pkill {name}",
             "windows": "Stop-Process -Name {name}"}},
    {"id": "kill_pid", "about": "stop a process by its id", "slots": ["pid"], "risk": "destructive",
     "say": ["kill process {pid}", "stop pid {pid}", "end process id {pid}"],
     "cmd": {"ubuntu": "kill {pid}", "fedora": "kill {pid}", "arch": "kill {pid}", "macos": "kill {pid}",
             "windows": "Stop-Process -Id {pid}"}},

    # ----- network -----
    {"id": "my_ip", "about": "this machine's IP address", "slots": [], "risk": "read",
     "say": ["what's my IP address", "show my local IP", "what IP am I on", "my network address"],
     "cmd": {"ubuntu": "ip -4 addr show", "fedora": "ip -4 addr show", "arch": "ip -4 addr show",
             "macos": "ipconfig getifaddr en0", "windows": "Get-NetIPAddress -AddressFamily IPv4"}},
    {"id": "public_ip", "about": "the IP the internet sees", "slots": [], "risk": "read",
     "say": ["what's my public IP", "what IP does the internet see", "my external IP address"],
     "cmd": {"ubuntu": "curl -s https://ifconfig.me", "fedora": "curl -s https://ifconfig.me", "arch": "curl -s https://ifconfig.me",
             "macos": "curl -s https://ifconfig.me", "windows": "Invoke-RestMethod https://ifconfig.me/ip"}},
    {"id": "port_users", "about": "what is listening on a port", "slots": ["port"], "risk": "read",
     "say": ["what's using port {port}", "who's on port {port}", "what's listening on {port}", "something is on port {port}, what"],
     "cmd": {"ubuntu": "sudo ss -ltnp 'sport = :{port}'", "fedora": "sudo ss -ltnp 'sport = :{port}'",
             "arch": "sudo ss -ltnp 'sport = :{port}'", "macos": "lsof -nP -iTCP:{port} -sTCP:LISTEN",
             "windows": "Get-NetTCPConnection -LocalPort {port} -State Listen"}},
    {"id": "all_listeners", "about": "everything listening for connections", "slots": [], "risk": "read",
     "say": ["what ports are open", "show everything listening", "list open ports on this machine"],
     "cmd": {"ubuntu": "sudo ss -ltnp", "fedora": "sudo ss -ltnp", "arch": "sudo ss -ltnp",
             "macos": "sudo lsof -nP -iTCP -sTCP:LISTEN", "windows": "Get-NetTCPConnection -State Listen"}},
    {"id": "ping_host", "about": "check a machine answers", "slots": ["host"], "risk": "read",
     "say": ["ping {host}", "is {host} up", "can I reach {host}", "check if {host} responds"],
     "cmd": {"ubuntu": "ping -c 4 {host}", "fedora": "ping -c 4 {host}", "arch": "ping -c 4 {host}", "macos": "ping -c 4 {host}",
             "windows": "Test-Connection {host} -Count 4"}},
    {"id": "dns_lookup", "about": "look up a name's address", "slots": ["host"], "risk": "read",
     "say": ["what IP is {host}", "dns lookup for {host}", "resolve {host}", "dig {host}"],
     "cmd": {"ubuntu": "dig +short {host}", "fedora": "dig +short {host}", "arch": "dig +short {host}", "macos": "dig +short {host}",
             "windows": "Resolve-DnsName {host}"}},
    {"id": "trace_route", "about": "the hops to a host", "slots": ["host"], "risk": "read",
     "say": ["traceroute {host}", "what path do packets take to {host}", "trace the route to {host}"],
     "cmd": {"ubuntu": "traceroute {host}", "fedora": "traceroute {host}", "arch": "traceroute {host}", "macos": "traceroute {host}",
             "windows": "tracert {host}"}},
    {"id": "download_file", "about": "download a file", "slots": ["url"], "risk": "write",
     "say": ["download {url}", "grab {url}", "fetch the file at {url}", "curl {url} to a file"],
     "cmd": {"ubuntu": "curl -LO {url}", "fedora": "curl -LO {url}", "arch": "curl -LO {url}", "macos": "curl -LO {url}",
             "windows": "Invoke-WebRequest -Uri {url} -OutFile (Split-Path {url} -Leaf)"}},
    {"id": "check_url", "about": "check a URL answers", "slots": ["url"], "risk": "read",
     "say": ["is {url} up", "check {url} responds", "what status does {url} return", "headers for {url}"],
     "cmd": {"ubuntu": "curl -I {url}", "fedora": "curl -I {url}", "arch": "curl -I {url}", "macos": "curl -I {url}",
             "windows": "Invoke-WebRequest -Uri {url} -Method Head"}},
    {"id": "ssh_host", "about": "log into another machine", "slots": ["user", "host"], "risk": "read",
     "say": ["ssh into {host} as {user}", "log into {host} as {user}", "connect to {user}@{host}"],
     "cmd": {"ubuntu": "ssh {user}@{host}", "fedora": "ssh {user}@{host}", "arch": "ssh {user}@{host}", "macos": "ssh {user}@{host}",
             "windows": "ssh {user}@{host}"}},
    {"id": "copy_to_host", "about": "copy a file to another machine", "slots": ["path", "user", "host"], "risk": "write",
     "say": ["copy {path} to {host}", "scp {path} to {user}@{host}", "send {path} over to {host} as {user}"],
     "cmd": {"ubuntu": "scp {path} {user}@{host}:~/", "fedora": "scp {path} {user}@{host}:~/", "arch": "scp {path} {user}@{host}:~/",
             "macos": "scp {path} {user}@{host}:~/", "windows": "scp {path} {user}@{host}:~/"}},
]

TASKS += [
    # ----- packages -----
    {"id": "install_pkg", "about": "install a program", "slots": ["pkg"], "risk": "install",
     "say": ["install {pkg}", "get {pkg} on this machine", "I need {pkg} installed", "add the {pkg} package"],
     "cmd": {"ubuntu": "sudo apt install -y {pkg}", "fedora": "sudo dnf install -y {pkg}", "arch": "sudo pacman -S --noconfirm {pkg}",
             "macos": "brew install {pkg}", "windows": "winget install --id {pkg} -e"}},
    {"id": "remove_pkg", "about": "uninstall a program", "slots": ["pkg"], "risk": "install",
     "say": ["uninstall {pkg}", "remove the {pkg} package", "get rid of {pkg}", "delete the program {pkg}"],
     "cmd": {"ubuntu": "sudo apt remove -y {pkg}", "fedora": "sudo dnf remove -y {pkg}", "arch": "sudo pacman -Rs --noconfirm {pkg}",
             "macos": "brew uninstall {pkg}", "windows": "winget uninstall --id {pkg} -e"}},
    {"id": "search_pkg", "about": "search for a package", "slots": ["pkg"], "risk": "read",
     "say": ["search for a package called {pkg}", "is there a {pkg} package", "look up {pkg} in the package manager"],
     "cmd": {"ubuntu": "apt search {pkg}", "fedora": "dnf search {pkg}", "arch": "pacman -Ss {pkg}", "macos": "brew search {pkg}",
             "windows": "winget search {pkg}"}},
    {"id": "update_index", "about": "refresh the package lists", "slots": [], "risk": "admin",
     "say": ["refresh the package list", "update the package index", "sync the repos"],
     "cmd": {"ubuntu": "sudo apt update", "fedora": "sudo dnf check-update", "arch": "sudo pacman -Sy", "macos": "brew update",
             "windows": "winget source update"}},
    {"id": "upgrade_all", "about": "update everything installed", "slots": [], "risk": "install",
     "say": ["update everything", "upgrade all my packages", "install the available updates"],
     "cmd": {"ubuntu": "sudo apt upgrade -y", "fedora": "sudo dnf upgrade -y", "arch": "sudo pacman -Syu --noconfirm",
             "macos": "brew upgrade", "windows": "winget upgrade --all"}},
    {"id": "list_installed", "about": "what's installed", "slots": [], "risk": "read",
     "say": ["what packages are installed", "list installed programs", "show me everything installed"],
     "cmd": {"ubuntu": "apt list --installed", "fedora": "dnf list installed", "arch": "pacman -Q", "macos": "brew list",
             "windows": "winget list"}},

    # ----- services -----
    {"id": "service_status", "about": "is a service running", "slots": ["svc"], "risk": "read",
     "say": ["is {svc} running", "status of the {svc} service", "check the {svc} service"],
     "cmd": {"ubuntu": "systemctl status {svc}", "fedora": "systemctl status {svc}", "arch": "systemctl status {svc}",
             "macos": "sudo launchctl print system/{svc}", "windows": "Get-Service {svc}"}},
    {"id": "service_start", "about": "start a service", "slots": ["svc"], "risk": "admin",
     "say": ["start {svc}", "bring up the {svc} service", "turn on {svc}"],
     "cmd": {"ubuntu": "sudo systemctl start {svc}", "fedora": "sudo systemctl start {svc}", "arch": "sudo systemctl start {svc}",
             "macos": "sudo launchctl kickstart system/{svc}", "windows": "Start-Service {svc}"}},
    {"id": "service_stop", "about": "stop a service", "slots": ["svc"], "risk": "admin",
     "say": ["stop {svc}", "shut down the {svc} service", "turn off {svc}"],
     "cmd": {"ubuntu": "sudo systemctl stop {svc}", "fedora": "sudo systemctl stop {svc}", "arch": "sudo systemctl stop {svc}",
             "macos": "sudo launchctl bootout system/{svc}", "windows": "Stop-Service {svc}"}},
    {"id": "service_restart", "about": "restart a service", "slots": ["svc"], "risk": "admin",
     "say": ["restart {svc}", "bounce the {svc} service", "restart the {svc} daemon"],
     "cmd": {"ubuntu": "sudo systemctl restart {svc}", "fedora": "sudo systemctl restart {svc}", "arch": "sudo systemctl restart {svc}",
             "macos": "sudo launchctl kickstart -k system/{svc}", "windows": "Restart-Service {svc}"}},
    {"id": "service_boot", "about": "start a service at boot", "slots": ["svc"], "risk": "admin",
     "say": ["start {svc} at boot", "enable {svc} on startup", "make {svc} run when the machine starts"],
     "cmd": {"ubuntu": "sudo systemctl enable {svc}", "fedora": "sudo systemctl enable {svc}", "arch": "sudo systemctl enable {svc}",
             "macos": "sudo launchctl enable system/{svc}", "windows": "Set-Service -Name {svc} -StartupType Automatic"}},
    {"id": "service_logs", "about": "a service's recent logs", "slots": ["svc"], "risk": "read",
     "say": ["logs for {svc}", "why did {svc} fail", "show the last {svc} log lines", "journal for {svc}"],
     "cmd": {"ubuntu": "journalctl -u {svc} -n 50 --no-pager", "fedora": "journalctl -u {svc} -n 50 --no-pager",
             "arch": "journalctl -u {svc} -n 50 --no-pager", "macos": "log show --predicate 'process == \"{svc}\"' --last 1h",
             "windows": "Get-WinEvent -LogName System -MaxEvents 50"}},

    # ----- system -----
    {"id": "os_version", "about": "which OS version this is", "slots": [], "risk": "read",
     "say": ["what OS is this", "which version am I running", "os version", "what distro is this"],
     "cmd": {"ubuntu": "cat /etc/os-release", "fedora": "cat /etc/os-release", "arch": "cat /etc/os-release", "macos": "sw_vers",
             "windows": "Get-ComputerInfo -Property OsName,OsVersion"}},
    {"id": "kernel_version", "about": "the kernel version", "slots": [], "risk": "read",
     "say": ["what kernel am I on", "kernel version", "uname"],
     "cmd": {"ubuntu": "uname -a", "fedora": "uname -a", "arch": "uname -a", "macos": "uname -a",
             "windows": "[System.Environment]::OSVersion.Version"}},
    {"id": "uptime", "about": "how long the machine has been up", "slots": [], "risk": "read",
     "say": ["how long has this been up", "uptime", "when did this machine last boot"],
     "cmd": {"ubuntu": "uptime", "fedora": "uptime", "arch": "uptime", "macos": "uptime",
             "windows": "(Get-CimInstance Win32_OperatingSystem).LastBootUpTime"}},
    {"id": "cpu_info", "about": "what CPU this machine has", "slots": [], "risk": "read",
     "say": ["what CPU is in here", "cpu info", "how many cores do I have"],
     "cmd": {"ubuntu": "lscpu", "fedora": "lscpu", "arch": "lscpu", "macos": "sysctl -n machdep.cpu.brand_string hw.ncpu",
             "windows": "Get-CimInstance Win32_Processor | Select-Object Name,NumberOfCores"}},
    {"id": "memory_info", "about": "how much memory is free", "slots": [], "risk": "read",
     "say": ["how much RAM is free", "memory usage", "how much memory does this machine have"],
     "cmd": {"ubuntu": "free -h", "fedora": "free -h", "arch": "free -h", "macos": "vm_stat",
             "windows": "Get-CimInstance Win32_OperatingSystem | Select-Object TotalVisibleMemorySize,FreePhysicalMemory"}},
    {"id": "hostname", "about": "this machine's name", "slots": [], "risk": "read",
     "say": ["what's this machine called", "hostname", "what's my computer name"],
     "cmd": {"ubuntu": "hostname", "fedora": "hostname", "arch": "hostname", "macos": "hostname", "windows": "hostname"}},
    {"id": "env_var", "about": "the value of an environment variable", "slots": ["var"], "risk": "read",
     "say": ["what is {var} set to", "print the {var} environment variable", "echo {var}"],
     "cmd": {"ubuntu": "printenv {var}", "fedora": "printenv {var}", "arch": "printenv {var}", "macos": "printenv {var}",
             "windows": "$env:{var}"}},
    {"id": "which_program", "about": "where a program lives", "slots": ["prog"], "risk": "read",
     "say": ["where is {prog} installed", "which {prog}", "do I have {prog}", "what's the path to {prog}"],
     "cmd": {"ubuntu": "command -v {prog}", "fedora": "command -v {prog}", "arch": "command -v {prog}", "macos": "command -v {prog}",
             "windows": "Get-Command {prog}"}},
    {"id": "whoami", "about": "which user this is", "slots": [], "risk": "read",
     "say": ["who am I logged in as", "whoami", "what user is this"],
     "cmd": {"ubuntu": "whoami", "fedora": "whoami", "arch": "whoami", "macos": "whoami", "windows": "whoami"}},
    {"id": "list_users", "about": "the accounts on this machine", "slots": [], "risk": "read",
     "say": ["list the users on this machine", "what accounts exist here", "show local users"],
     "cmd": {"ubuntu": "cut -d: -f1 /etc/passwd", "fedora": "cut -d: -f1 /etc/passwd", "arch": "cut -d: -f1 /etc/passwd",
             "macos": "dscl . list /Users | grep -v '^_'", "windows": "Get-LocalUser"}},
    {"id": "add_user", "about": "make a new account", "slots": ["user"], "risk": "admin",
     "say": ["add a user called {user}", "create the account {user}", "make a new user {user}"],
     "cmd": {"ubuntu": "sudo adduser {user}", "fedora": "sudo useradd -m {user}", "arch": "sudo useradd -m {user}",
             "macos": "sudo sysadminctl -addUser {user}", "windows": "New-LocalUser -Name {user}"}},
    {"id": "reboot", "about": "restart the machine", "slots": [], "risk": "destructive",
     "say": ["reboot", "restart this machine", "reboot the computer now"],
     "cmd": {"ubuntu": "sudo reboot", "fedora": "sudo reboot", "arch": "sudo reboot", "macos": "sudo shutdown -r now",
             "windows": "Restart-Computer"}},

    # ----- archives -----
    {"id": "zip_folder", "about": "zip a folder", "slots": ["path"], "risk": "write",
     "say": ["zip up {path}", "make a zip of {path}", "compress {path} into a zip"],
     "cmd": {"ubuntu": "zip -r {path}.zip {path}", "fedora": "zip -r {path}.zip {path}", "arch": "zip -r {path}.zip {path}",
             "macos": "zip -r {path}.zip {path}", "windows": "Compress-Archive -Path {path} -DestinationPath {path}.zip"}},
    {"id": "unzip_file", "about": "unpack a zip", "slots": ["path"], "risk": "write",
     "say": ["unzip {path}", "extract {path}", "unpack the zip {path}"],
     "cmd": {"ubuntu": "unzip {path}", "fedora": "unzip {path}", "arch": "unzip {path}", "macos": "unzip {path}",
             "windows": "Expand-Archive -Path {path} -DestinationPath ."}},
    {"id": "tar_create", "about": "make a tar.gz", "slots": ["path"], "risk": "write",
     "say": ["tar up {path}", "make a tar.gz of {path}", "archive {path} with tar"],
     "cmd": {"ubuntu": "tar -czf {path}.tar.gz {path}", "fedora": "tar -czf {path}.tar.gz {path}",
             "arch": "tar -czf {path}.tar.gz {path}", "macos": "tar -czf {path}.tar.gz {path}",
             "windows": "tar -czf {path}.tar.gz {path}"}},
    {"id": "tar_extract", "about": "unpack a tar.gz", "slots": ["path"], "risk": "write",
     "say": ["extract {path}", "untar {path}", "unpack the archive {path}"],
     "cmd": {"ubuntu": "tar -xzf {path}", "fedora": "tar -xzf {path}", "arch": "tar -xzf {path}", "macos": "tar -xzf {path}",
             "windows": "tar -xzf {path}"}},

    # ----- git and dev -----
    {"id": "git_clone", "about": "clone a repository", "slots": ["url"], "risk": "write",
     "say": ["clone {url}", "git clone {url}", "grab the repo at {url}"],
     "cmd": {"ubuntu": "git clone {url}", "fedora": "git clone {url}", "arch": "git clone {url}", "macos": "git clone {url}",
             "windows": "git clone {url}"}},
    {"id": "git_status", "about": "what's changed in a repo", "slots": [], "risk": "read",
     "say": ["what's changed here", "git status", "show me the working tree state"],
     "cmd": {"ubuntu": "git status", "fedora": "git status", "arch": "git status", "macos": "git status", "windows": "git status"}},
    {"id": "git_log", "about": "recent commits", "slots": [], "risk": "read",
     "say": ["show the last commits", "git log", "what were the recent changes"],
     "cmd": {"ubuntu": "git log --oneline -10", "fedora": "git log --oneline -10", "arch": "git log --oneline -10",
             "macos": "git log --oneline -10", "windows": "git log --oneline -10"}},
    {"id": "python_version", "about": "which Python is installed", "slots": [], "risk": "read",
     "say": ["what python version do I have", "python version", "which python is installed"],
     "cmd": {"ubuntu": "python3 --version", "fedora": "python3 --version", "arch": "python3 --version", "macos": "python3 --version",
             "windows": "python --version"}},
    {"id": "pip_install", "about": "install a Python package", "slots": ["pkg"], "risk": "install",
     "say": ["pip install {pkg}", "install the python package {pkg}", "add {pkg} to python"],
     "cmd": {"ubuntu": "python3 -m pip install {pkg}", "fedora": "python3 -m pip install {pkg}", "arch": "python3 -m pip install {pkg}",
             "macos": "python3 -m pip install {pkg}", "windows": "python -m pip install {pkg}"}},
    {"id": "make_venv", "about": "make a Python virtual environment", "slots": [], "risk": "write",
     "say": ["make a virtualenv", "set up a venv here", "create a python virtual environment"],
     "cmd": {"ubuntu": "python3 -m venv .venv", "fedora": "python3 -m venv .venv", "arch": "python3 -m venv .venv",
             "macos": "python3 -m venv .venv", "windows": "python -m venv .venv"}},
    {"id": "serve_folder", "about": "serve this folder over HTTP", "slots": ["port"], "risk": "read",
     "say": ["serve this folder on port {port}", "start a web server here on {port}", "http server on port {port}"],
     "cmd": {"ubuntu": "python3 -m http.server {port}", "fedora": "python3 -m http.server {port}", "arch": "python3 -m http.server {port}",
             "macos": "python3 -m http.server {port}", "windows": "python -m http.server {port}"}},

    # ----- text -----
    {"id": "sort_file", "about": "sort a file's lines", "slots": ["path"], "risk": "read",
     "say": ["sort {path}", "show {path} in order", "sort the lines of {path}"],
     "cmd": {"ubuntu": "sort {path}", "fedora": "sort {path}", "arch": "sort {path}", "macos": "sort {path}",
             "windows": "Get-Content {path} | Sort-Object"}},
    {"id": "unique_lines", "about": "the unique lines in a file", "slots": ["path"], "risk": "read",
     "say": ["unique lines in {path}", "dedupe {path}", "remove duplicate lines from {path}"],
     "cmd": {"ubuntu": "sort -u {path}", "fedora": "sort -u {path}", "arch": "sort -u {path}", "macos": "sort -u {path}",
             "windows": "Get-Content {path} | Sort-Object -Unique"}},

    # ----- misc -----
    {"id": "open_folder", "about": "open this folder in the desktop file browser", "slots": [], "risk": "read",
     "say": ["open this folder", "show this in the file browser", "open the current directory in finder"],
     "cmd": {"ubuntu": "xdg-open .", "fedora": "xdg-open .", "arch": "xdg-open .", "macos": "open .", "windows": "Invoke-Item ."}},
    {"id": "copy_clipboard", "about": "copy a file's contents to the clipboard", "slots": ["path"], "risk": "read",
     "say": ["copy {path} to the clipboard", "put the contents of {path} on my clipboard"],
     "cmd": {"ubuntu": "xclip -selection clipboard < {path}", "fedora": "xclip -selection clipboard < {path}",
             "arch": "xclip -selection clipboard < {path}", "macos": "pbcopy < {path}",
             "windows": "Get-Content {path} | Set-Clipboard"}},
    {"id": "scheduled_jobs", "about": "what's scheduled to run", "slots": [], "risk": "read",
     "say": ["what cron jobs do I have", "list scheduled tasks", "show my crontab"],
     "cmd": {"ubuntu": "crontab -l", "fedora": "crontab -l", "arch": "crontab -l", "macos": "crontab -l",
             "windows": "Get-ScheduledTask"}},
    {"id": "firewall_status", "about": "is the firewall on", "slots": [], "risk": "read",
     "say": ["is the firewall on", "firewall status", "check my firewall"],
     "cmd": {"ubuntu": "sudo ufw status", "fedora": "sudo firewall-cmd --state", "arch": "sudo iptables -L -n",
             "macos": "sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate",
             "windows": "Get-NetFirewallProfile | Select-Object Name,Enabled"}},
]
